apiVersion: v2
appVersion: v4
dependencies:
- name: redis
  repository: https://charts.bitnami.com
  version: 10.x.x
description: A chart for deploying the Guestbook tutorial application, including a
  PHP frontend and a Redis backend.
home: https://kubernetes.io/docs/tutorials/stateless-application/guestbook/
maintainers:
- name: PacktPublishing
name: guestbook-advanced
version: 1.0.0
