apiVersion: charts.helm.k8s.io/v1alpha1
kind: Guestbook
metadata:
  name: example-guestbook
spec:
  # Default values copied from <project_dir>/helm-charts/guestbook-advanced/values.yaml
  
  guestbookReplicas: 2
  healthchecks:
    enabled: true
    port: 80
  image:
    registry: gcr.io
    repository: google-samples/gb-frontend
    tag: v4
  redis:
    configmap: |-
      appendonly no
      save ""
    master:
      persistence:
        size: 1Gi
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    slave:
      persistence:
        size: 1Gi
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    usePassword: false
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
  servicePorts:
  - 80
  serviceType: NodePort
  
